version: "3.3"
services:
  db:
    image: "postgres:15-alpine"
    env_file:
      - ./MAOL/.env
    ports:
      - 5432:5432
    volumes: 
      - db:/var/lib/postgresql/data
  web:
    build: .
    image: my-anime-openings-list_web
    env_file:
      - ./MAOL/.env
    ports:
      - 443:443
    depends_on:
      - db

volumes:
  db:
    driver: local