version: "3.3"
services:
  db:
    image: "postgres:15-alpine"
    env_file:
      - ./MAOL/.env
    ports:
      - 5432:5432
    volumes: 
      - db:/var/lib/postgresql/data
  web:
    build: .
    env_file:
      - ./MAOL/.env
    ports:
      - 80:80
    depends_on:
      - db

volumes:
  db:
    driver: local