# Generated by Django 3.2.4 on 2021-06-30 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('studio', models.TextField()),
                ('mal_link', models.TextField(default='', verbose_name='MyAnimeList Link')),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_type', models.CharField(choices=[('OP', 'Opening'), ('ED', 'Ending'), ('OST', 'Soundtrack')], max_length=3)),
                ('name', models.TextField()),
                ('artist', models.TextField()),
                ('youtube_link', models.TextField(default='')),
                ('number', models.TextField()),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.anime')),
            ],
        ),
    ]
