# Generated by Django 3.2.4 on 2021-07-01 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_list', '0002_remove_songlist_songs'),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='belongs_to_lists',
            field=models.ManyToManyField(through='personal_list.SongRating', to='personal_list.SongList'),
        ),
    ]
