# Generated by Django 3.2.4 on 2021-07-20 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_song_belongs_to_lists'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='youtube_link',
            new_name='video_link',
        ),
        migrations.AddField(
            model_name='song',
            name='embed_link',
            field=models.TextField(default=''),
        ),
    ]
