# Generated by Django 3.2.4 on 2021-07-22 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20210720_1443'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anime',
            old_name='name',
            new_name='japanese_name',
        ),
        migrations.RemoveField(
            model_name='anime',
            name='mal_link',
        ),
        migrations.AddField(
            model_name='anime',
            name='anilist_link',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='anime',
            name='english_name',
            field=models.TextField(default='a'),
            preserve_default=False,
        ),
    ]
