# Generated by Django 3.2.4 on 2021-07-22 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_song_embed_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='artist',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='song',
            name='name',
            field=models.TextField(default=''),
        ),
    ]
