# Generated by Django 3.2.4 on 2021-07-22 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20210722_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='cover',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='anime',
            name='anilist_link',
            field=models.TextField(),
        ),
    ]
