# Generated by Django 3.2.4 on 2021-10-02 04:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20210722_2129'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 2, 4, 28, 52, 921723, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='anime',
            name='last_modified',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 2, 4, 28, 57, 13216, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='song',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 2, 4, 29, 11, 123538, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='song',
            name='last_modified',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 2, 4, 29, 14, 809165, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
