# Generated by Django 3.2.4 on 2022-04-08 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20211002_2229'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='slug_name',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
