# Generated by Django 3.2.4 on 2022-04-09 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_anime_slug_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='song_type',
            field=models.CharField(choices=[('OP', 'Opening'), ('ED', 'Ending'), ('OST', 'Soundtrack')], max_length=10),
        ),
    ]
