# Generated by Django 3.2.4 on 2022-04-09 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_song_song_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='detail_link',
            field=models.TextField(default=''),
        ),
    ]
