# Generated by Django 3.2.4 on 2021-07-01 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal_list', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='songlist',
            name='songs',
        ),
    ]
