# Generated by Django 3.2.4 on 2021-07-01 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_list', '0002_remove_songlist_songs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songrating',
            name='rating',
            field=models.CharField(choices=[('1', 'Appalling'), ('2', 'Horrible'), ('3', 'Very Bad'), ('4', 'Bad'), ('5', 'Average'), ('6', 'Fine'), ('7', 'Good'), ('8', 'Very Good'), ('9', 'Great'), ('10', 'Masterpiece')], default='5', max_length=2),
        ),
    ]
