# Generated by Django 3.2.4 on 2021-10-02 05:34

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('personal_list', '0003_alter_songrating_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='songlist',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 2, 5, 34, 9, 293852, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='songlist',
            name='last_modified',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 2, 5, 34, 13, 997246, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='songrating',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 2, 5, 34, 17, 629333, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='songrating',
            name='last_modified',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 2, 5, 34, 21, 131300, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='songrating',
            name='rating',
            field=models.CharField(blank=True, choices=[('1', 'Appalling'), ('2', 'Horrible'), ('3', 'Very Bad'), ('4', 'Bad'), ('5', 'Average'), ('6', 'Fine'), ('7', 'Good'), ('8', 'Very Good'), ('9', 'Great'), ('10', 'Masterpiece')], max_length=2, null=True),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField()),
                ('last_modified', models.DateTimeField()),
                ('avatar', models.ImageField(upload_to='avatars')),
                ('banner', models.ImageField(upload_to='banners')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
