# Generated by Django 3.2.4 on 2021-10-02 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal_list', '0005_auto_20211002_1658'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='last_modified',
        ),
    ]
