# Generated by Django 3.2.4 on 2021-10-02 12:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('personal_list', '0006_auto_20211002_2216'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 2, 12, 20, 54, 124134, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='last_modified',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 2, 12, 21, 5, 433981, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
