# Generated by Django 3.2.4 on 2021-10-03 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal_list', '0008_auto_20211002_2229'),
    ]

    operations = [
        migrations.RenameField(
            model_name='songlist',
            old_name='owner',
            new_name='user',
        ),
    ]
