# Generated by Django 3.2.4 on 2021-10-03 10:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_list', '0009_rename_owner_songlist_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songrating',
            name='rating',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(10)]),
        ),
    ]
