# Generated by Django 3.2.4 on 2021-10-15 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_list', '0010_alter_songrating_rating'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='songrating',
            constraint=models.UniqueConstraint(fields=('parent_list', 'song'), name='one_rating_only'),
        ),
    ]
